# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative 'config/application'

Rails.application.load_tasks

task backfill: :environment do
  events = FourthDimensional::EventLoaders::ActiveRecord::Event.order(:version).map do |event|
    FourthDimensional.config.event_loader.deserialize_event(event)
  end

  Products::ProductProjector.call(events)
end
